-- MySQL Script generated by MySQL Workbench
-- Thu 03 Nov 2016 15:34:16 SAST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Matcha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Matcha` ;
USE `Matcha` ;

-- -----------------------------------------------------
-- Table `Matcha`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`user` (
  `username` VARCHAR(16) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(72) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `uid` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`message` (
  `idmessage` BIGINT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `Sent` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Sender` INT NULL,
  `Receiver` INT NULL,
  `Seen` CHAR NULL DEFAULT 'N',
  PRIMARY KEY (`idmessage`),
  INDEX `Sender_idx` (`Sender` ASC),
  INDEX `Receiver_idx` (`Receiver` ASC),
  CONSTRAINT `Sender`
    FOREIGN KEY (`Sender`)
    REFERENCES `Matcha`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Receiver`
    FOREIGN KEY (`Receiver`)
    REFERENCES `Matcha`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`Flirts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`Flirts` (
  `idF` BIGINT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `Interest` INT NOT NULL,
  `Found` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Matched` CHAR NULL DEFAULT 'N',
  PRIMARY KEY (`idF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`info` (
  `iid` INT NOT NULL,
  `dateofbirth` DATE NULL,
  `cell` VARCHAR(15) NULL DEFAULT '+27600000000',
  `tel` VARCHAR(15) NULL DEFAULT '+27310000000',
  `preference` VARCHAR(2) NULL,
  `sex` VARCHAR(2) NULL DEFAULT 'A',
  `otherSocial` VARCHAR(45) NULL,
  `Bio` TEXT NULL,
  `country` VARCHAR(20) NULL DEFAULT 'South Africa',
  `city` VARCHAR(25) NULL DEFAULT 'Durban',
  `location_history` VARCHAR(20) NULL,
  `location_last` VARCHAR(20) NULL,
  `Interests` TEXT NULL,
  PRIMARY KEY (`iid`),
  CONSTRAINT `uid`
    FOREIGN KEY (`iid`)
    REFERENCES `Matcha`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE DEFINER = CURRENT_USER TRIGGER `Matcha`.`user_AFTER_INSERT` AFTER INSERT ON `user` FOR EACH ROW
BEGIN
	insert into Matcha.info (iid) select  new.uid from Matcha.user;
END

